# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ======== shape вывела размерность матрицы
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.41676978 0.44652117 0.67887951 ... 0.71831432 0.37194733 0.19513275]
 [0.75212648 0.97360094 0.69519096 ... 0.70148708 0.52070477 0.20898826]
 [0.52401808 0.38820823 0.87648811 ... 0.44084258 0.93498734 0.13448892]
 ...
 [0.04942381 0.84563429 0.8975699  ... 0.11078114 0.62940574 0.05290682]
 [0.54136984 0.46493132 0.75764089 ... 0.29487853 0.80090707 0.33453056]
 [0.65091819 0.50255655 0.47593216 ... 0.72649616 0.4486456  0.59223577]]
[[0.69551521 0.93189364 0.0422657  ... 0.72308025 0.68175787 0.368898  ]
 [0.73069486 0.92290442 0.6790813  ... 0.16366662 0.13215747 0.71808433]
 [0.34623017 0.00187521 0.41257603 ... 0.23477836 0.11879222 0.65466753]
 ...
 [0.48262469 0.16217724 0.54808738 ... 0.34443785 0.52908681 0.06464463]
 [0.99246893 0.90578576 0.862693   ... 0.10745736 0.34290093 0.68099965]
 [0.56323226 0.58457769 0.13437903 ... 0.01568438 0.10746438 0.07635202]]


Без использования numpy

In [ ]:
def mult(a, b):
    if len(a[0]) != len(b):
        print("Невозможно умножить матрицы: неподходящие размерности")
        return None

    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]

    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 704 ms, sys: 2.57 ms, total: 706 ms
Wall time: 712 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 0 ns, sys: 1.12 ms, total: 1.12 ms
Wall time: 9.11 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.531574866930896e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.71587628 0.20566514 0.32403878] [0.39762362 0.73901754 0.98159955]


In [ ]:
def scalar_product(a, b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [ ]:
def np_scalar_product(a, b):
    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 24 µs, sys: 0 ns, total: 24 µs
Wall time: 27.9 µs
CPU times: user 83 µs, sys: 0 ns, total: 83 µs
Wall time: 188 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** numpy выполняет операции сразу над целыми массивами данных без необходимости использования циклов_______________________________

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diag_elements = np.diag(a)
    even_diag_elements = diag_elements[diag_elements % 2 == 0]

    if len(even_diag_elements) > 0:
        res = np.sum(even_diag_elements)
    else:
        res = 0

    return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 255 µs, sys: 0 ns, total: 255 µs
Wall time: 263 µs


16

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result_list = []
    for arr in A:
        cum_sum = np.cumsum(arr)
        result = cum_sum / np.arange(1, len(arr) + 1)
        result_list.append(result)

    return np.array(result_list)

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.36706911 0.23763355 0.12763101 0.6429496  0.83258017 0.48790317
 0.33965628 0.2877202  0.01439122 0.99745647 0.67350484 0.88775594
 0.15090027 0.76510914 0.40768389 0.48203844 0.08095149 0.41502834
 0.87451407 0.70007834 0.75580805 0.72129383 0.77000276 0.13099274
 0.08525893 0.32262817 0.76697212 0.95166876 0.04552278 0.4205165
 0.87511612 0.35297493 0.68895486 0.31967481 0.88584167 0.75464713
 0.89557757 0.96528406 0.95779298 0.43583325 0.89009556 0.62791969
 0.50888357 0.07635243 0.90908896 0.03287179 0.17444729 0.35674227
 0.47810051 0.37450995 0.3686637  0.45991153 0.9726337  0.24878999
 0.18432156 0.21771479 0.23669739 0.11061939 0.593236   0.28551819
 0.58766583 0.9545832  0.71465182 0.40231702 0.94708787 0.08274253
 0.27249252 0.62991683 0.42166844 0.17811928 0.19115057 0.842552
 0.51860357 0.49155929 0.16495067 0.89521801 0.67372876 0.20587567
 0.74903682 0.2847698  0.0198524  0.01639454 0.70673495 0.62746458
 0.80558773 0.29859608 0.42987758 0.39450559 0.21990267 0.5982841

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
def np_encode(a):
    elements = []
    counts = []

    current_element = a[0]
    count = 1

    for i in range(1, len(a)):
        if a[i] == current_element:
            count += 1
        else:
            elements.append(current_element)
            counts.append(count)

            current_element = a[i]
            count = 1

    elements.append(current_element)
    counts.append(count)

    return np.array(elements), np.array(counts)

X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)
print("Результат:")
print("Элементы:", x)
print("Количество повторений:", num)

CPU times: user 26 µs, sys: 4 µs, total: 30 µs
Wall time: 34.8 µs
Результат:
Элементы: [1 2 3 1 5 2 3]
Количество повторений: [1 2 2 2 2 1 2]


In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 42.4 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    transformed_X = np.copy(X)

    transformed_X[1::2] = a

    transformed_X[::2] **= 3

    transformed_X = transformed_X[::-1]

    merged_array = np.concatenate((X, transformed_X))

    result = merged_array[::1]

    return result


X = np.array([100, 200, 300, 400, 500])
%time result = np_transformation(X)
print(result)

CPU times: user 144 µs, sys: 0 ns, total: 144 µs
Wall time: 131 µs
[      100       200       300       400       500 125000000         1
  27000000         1   1000000]


In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 97 µs, sys: 15 µs, total: 112 µs
Wall time: 100 µs
